### ISSUE TITLE
HTTP Toolkit not open

### ISSUE THREAD

**Issue by anwarmaxa2011** [httptoolkit/httptoolkit-desktop#66] opened 2024-03-18 21:33 UTC
HTTP Toolkit not open win 7 
It was working and now it does not open. This message appears. I scanned and installed the latest version and the same thing
![Capture](https://github.com/httptoolkit/httptoolkit-desktop/assets/163927695/48fe6883-3577-4945-9fbe-727d1c37afea)

**Comment by pimterry** [comment] 2024-03-19 10:11
This is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/243. Please search for existing reports before opening new ones.

This error is happens because Windows 7 is no longer supported.

On Windows, HTTP Toolkit only supports version 8.1 or newer. Older versions of Windows are no longer supported even by Microsoft, and have not been for many years. In HTTP Toolkit's case, this cannot be supported because some components we use internally (notably Node.js) no longer support Windows 7. You'll need to update to at least Windows 8.1 to use HTTP Toolkit (but I'd recommend moving to Windows 10+, since Windows 8.1 has since reached official end-of-life too in January 2023, and may not be supported either soon). You can check Microsoft's end-of-life support dates for Windows here: https://endoflife.date/windows

**Closed by pimterry** 2024-03-19 10:11 UTC
