### ISSUE TITLE
Hi, can you add dark mode please? Everything is way too bright. Thanks.

### ISSUE THREAD

**Issue by Michael-Github-2023** [httptoolkit/httptoolkit-desktop#63] opened 2023-11-29 19:37 UTC
Hi, can you add dark mode please? Everything is way too bright. Thanks.

**Comment by pimterry** [comment] 2023-11-29 19:39
Hi @Michael-Github-2023 :smile:. This is a duplicate of https://github.com/httptoolkit/httptoolkit/issues/183 - I'll close this issue, but do take a look at the comments there for some context.

**Closed by pimterry** 2023-11-29 19:39 UTC
