### ISSUE TITLE
npm run start:dev fails to start

### ISSUE THREAD

**Issue by lionelhorn** [httptoolkit/httptoolkit-desktop#54] opened 2023-03-10 17:31 UTC
I'm trying to figure out how to add features like using existing chrome profiles.

So I tried to setup a local dev env following: https://github.com/httptoolkit/httptoolkit-desktop#contributing

It first seemed to miss "tslib" as a deps

I first tried: 
```shell
npm run start:dev
```

It failed so I tried to run the separate steps from 
` npm run server:setup && npm run start:app`

`npm run server:setup 👍 `
```shell
> httptoolkit-desktop@1.12.3 server:setup C:\PROG\Tests\_httptoolkit\httptoolkit-desktop
> ts-node ./setup-server.ts

Downloading httptoolkit-server v1.12.3 for win32-x64
Downloading server from https://github.com/httptoolkit/httptoolkit-server/releases/download/v1.12.3/httptoolkit-server-v1.12.3-win32-x64.tar.gz...
Extracting server to C:\PROG\Tests\_httptoolkit\httptoolkit-desktop
Server download completed
Server setup completed.

Process finished with exit code 0
```

`npm run start:app => 👎 `
```shell
6:25:24 PM - Starting compilation in watch mode...

error TS6054: File '.'' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

6:25:27 PM - Found 1 error. Watching for file changes.
```

Desktop app doesn't start.

**Comment by pimterry** [comment] 2023-03-13 14:55
Not sure I'm afraid. I'm fairly confident the setup works generally (it works for me locally, and for starters the CI build installs & runs very similar steps successfully) but it's hard to know exactly what could cause the above on your machine.

Can you share the node, npm & Windows versions you're using, and the exact steps you're running (from `git clone` onwards) so I can reproduce this for myself?

**Comment by pimterry** [comment] 2023-03-13 14:58
> I'm trying to figure out how to add features like using existing chrome profiles.

Oh, and the above would be useful info to ensure this is working properly regardless, but actually I think you probably don't need to use this repo for that case. This repo provides the desktop shell, which affects the end application UX and installation process, but it doesn't have the implementation of interception features like existing chrome interception etc.

The backend for that lives in [httptoolkit-server](https://github.com/httptoolkit/httptoolkit-server/) while the UI for interceptors (mostly just buttons, but some have more complex behaviour) lives in [httptoolkit-ui](https://github.com/httptoolkit/httptoolkit-ui/). You can run either/both of those independently and then just open the UI in a normal browser without the desktop shell bits on top. See the readme for each for instructions on how to do that.

**Comment by pimterry** [comment] 2023-03-24 13:34
Thanks for all the details @lionelhorn! Very helpful.

> This syntax requires an imported helper but module 'tslib' cannot be found.

I think this must be due to how pnpm manages packages, it looks like in effect we had an implicit dependency on that, which works fine with npm via transitive dependencies, but fails with pnpm. I've just [added that](https://github.com/httptoolkit/httptoolkit-desktop/commit/6b59e5f3d75f970599deabf49ec61ba94da5e85f) as an explicit dependency which should resolve this. Let me know if you're still seeing pnpm issues after updating to use that.

> File '.'' has an unsupported extension.

No idea why that'd happen, it must be some kind of shell difference (as you say, it works in WSL). I think this must be caused by the `electron .` command that's run, but I think that command is actually correct... The electron CLI help says you have to provide an argument pointing to an Electron app, and a "Folder containing a package.json file" is a valid option.

If you can work out a different command for "run this directory as an electron app" that _does_ work for Powershell, without breaking anything else, a PR to switch to that would be much appreciated!

**Comment by pimterry** [comment] 2023-07-03 17:14
Ok, I still have no idea what causes this, but I've somehow managed to reproduce it in a Windows VM. It seems to be to do with the quotes in that npm script, and escaping double quotes does resolve the issue, for me at least, as here: https://github.com/httptoolkit/httptoolkit-desktop/commit/d9f25199d041a91e44955313f9f84fff86cacccb.

I'm assuming this will also fix that for you (and any others) so I'm going to close this, but do please reply here if you're still having issues with this after that fix.

**Closed by pimterry** 2023-07-03 17:14 UTC
